# Generated by Django 3.2.15 on 2022-08-11 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=128, verbose_name='模块名称')),
                ('package_name', models.CharField(max_length=128, verbose_name='包名')),
                ('enabled_flag', models.CharField(choices=[(0, '禁用'), (1, '启用')], max_length=31, verbose_name='启用标记')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 799132), verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 799132), verbose_name='修改时间')),
                ('mod_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('mod_developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_developer', to=settings.AUTH_USER_MODEL, verbose_name='开发人员')),
                ('mod_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_principal', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块列表',
            },
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('product_line', models.CharField(choices=[(0, 'FMS系统'), (1, 'CRM系统'), (2, 'TMS系统'), (3, 'COO系统')], max_length=32, verbose_name='产品线')),
                ('enabled_flag', models.CharField(choices=[(0, '禁用'), (1, '启用')], max_length=31, verbose_name='启用标记')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 798133), verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 798133), verbose_name='修改时间')),
                ('pro_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('pro_developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_developer', to=settings.AUTH_USER_MODEL, verbose_name='开发人员')),
                ('pro_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_principal', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('pro_tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_tester', to=settings.AUTH_USER_MODEL, verbose_name='测试人员')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目列表',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=128, verbose_name='套件名称')),
                ('case_set', models.TextField(max_length=2048, verbose_name='用例集')),
                ('enabled_flag', models.CharField(choices=[(0, '禁用'), (1, '启用')], max_length=31, verbose_name='启用标记')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 807055), verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 807055), verbose_name='修改时间')),
                ('describe', models.TextField(max_length=1024, verbose_name='描述')),
                ('suite_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('suite_modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('suite_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_project', to='case.projectlist', verbose_name='归属项目')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='优先级')),
                ('api_code', models.CharField(max_length=256, verbose_name='接口code')),
                ('parameter', models.TextField(max_length=1024, verbose_name='参数')),
                ('headers', models.TextField(max_length=1024, verbose_name='请求头')),
                ('status', models.CharField(max_length=32, verbose_name='用例状态')),
                ('enabled_flag', models.CharField(choices=[(0, '禁用'), (1, '启用')], max_length=31, verbose_name='启用标记')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 799867), verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 20, 54, 799867), verbose_name='修改时间')),
                ('case_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('case_modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('case_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.modulelist', verbose_name='模块')),
                ('case_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_project', to='case.projectlist', verbose_name='归属项目')),
            ],
        ),
        migrations.AddField(
            model_name='modulelist',
            name='mod_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_project', to='case.projectlist', verbose_name='归属项目'),
        ),
    ]
