# Generated by Django 3.2.15 on 2022-08-11 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 592212), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='modulelist',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 592212), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 591212), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 591212), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 592212), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 592212), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 599212), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 22, 19, 599212), verbose_name='修改时间'),
        ),
    ]
