# Generated by Django 3.2.15 on 2022-08-11 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20220811_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '用例', 'verbose_name_plural': '用例列表'},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'verbose_name': '测试套件', 'verbose_name_plural': '套件列表'},
        ),
        migrations.AlterField(
            model_name='modulelist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 835481), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='modulelist',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 835481), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 834482), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 834482), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 835481), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 835481), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 844907), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 24, 16, 844907), verbose_name='修改时间'),
        ),
    ]
